name: Build Dev Container (dev-general)

on:
  push:
    branches: [main, master]
    paths:
      - 'devcontainer/dev-general/**'
      - '.github/workflows/build-devcontainer.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'devcontainer/dev-general/**'
      - '.github/workflows/build-devcontainer.yml'
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build-and-scan:
    uses: ./.github/workflows/template-build-scan.yml
    with:
      image_name: 'dev-general'
      context: './devcontainer/dev-general'
      dockerfile: './devcontainer/dev-general/Containerfile'
    secrets: inherit