name: Build Dev Container (dev-media)

on:
  push:
    branches: [main, master]
    paths:
      - 'devcontainer/dev-media/**'
      - '.github/workflows/build-devcontainer-media.yml'
  pull_request:
    branches: [main, master]
    paths:
      - 'devcontainer/dev-media/**'
      - '.github/workflows/build-devcontainer-media.yml'
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build-and-scan:
    uses: ./.github/workflows/template-build-scan.yml
    with:
      image_name: 'dev-media'
      context: './devcontainer/dev-media'
      dockerfile: './devcontainer/dev-media/Containerfile'
    secrets: inherit